# Generated by Django 6.0.3 on 2026-03-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual salary in INR (required)', max_digits=12),
            preserve_default=False,
        ),
    ]
