# Generated by Django 6.0.1 on 2026-03-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_walk_in',
            field=models.BooleanField(default=False, help_text='Whether this job accepts direct walk-ins'),
        ),
        migrations.AddField(
            model_name='job',
            name='walk_in_address',
            field=models.TextField(blank=True, default='', help_text='Physical address for walk-in candidates'),
        ),
    ]
