# Generated by Django 6.0.3 on 2026-03-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_is_walk_in_job_walk_in_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Contact email for employers', max_length=254),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Contact phone number', max_length=20),
        ),
    ]
