# Generated by Django 6.0.1 on 2026-03-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_candidateprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='HR Name', max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='Contact Number', max_length=20),
        ),
    ]
