# Generated by Django 6.0.1 on 2026-03-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_employerprofile_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='HR Email', max_length=254),
        ),
    ]
