# Generated by Django 6.0.1 on 2026-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_employerprofile_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='about',
            field=models.TextField(blank=True, default='', help_text='About the candidate'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='social_links',
            field=models.TextField(blank=True, default='', help_text='Portfolio, LinkedIn, GitHub links'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='about',
            field=models.TextField(blank=True, default='', help_text='About the company'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='org_details',
            field=models.TextField(blank=True, default='', help_text='Organization size, type, or other details'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='website_links',
            field=models.TextField(blank=True, default='', help_text='Company website or social links'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
