# Generated by Django 6.0.1 on 2026-04-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_candidateprofile_about_candidateprofile_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
