# Generated by Django 6.0.1 on 2026-04-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_candidateprofile_city_employerprofile_city_job_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the job expires and should be deleted', null=True),
        ),
    ]
