# Generated by Django 6.0.1 on 2026-04-06 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
