# Generated by Django 6.0.1 on 2026-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_candidateprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional job description'),
        ),
    ]
