# Generated by Django 6.0.3 on 2026-04-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_ats_score',
            field=models.FloatField(blank=True, help_text='ATS standard score (0-100) generated by AI', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_experience',
            field=models.IntegerField(blank=True, help_text='Experience extracted by AI', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Uploaded resume PDF', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_parsed_skills',
            field=models.TextField(blank=True, default='', help_text='Skills extracted by AI'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_summary',
            field=models.TextField(blank=True, default='', help_text='General resume strength summary by AI'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_text',
            field=models.TextField(blank=True, default='', help_text='Extracted completely raw text from resume'),
        ),
    ]
